### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pazos** [unwmun/refreshU#1]
Hi @unwmun, I wonder if I can use part of your code in [KOReader](https://github.com/koreader/koreader) instead of relying on onyx sdk sources. I'm talking about the device abstraction & EPD Controller. Actually I'm using onyx sdk but their sources are bloated with features that we aren't going to use.

KOReader is AGPL3 licensed, but I want to merge the code in [android-luajit-launcher](https://github.com/koreader/android-luajit-launcher), which is used to launch a lua native activity on android, and is MIT licensed.

If you allow the merge then I would pull the git history for the [epdcontrol folder](https://github.com/unwmun/refreshU/tree/master/epdcontrol/src/main/java/com/unw/device/epdcontrol).

Thanks for your time!!!

**Comment by unwmun** [comment]
Hi @pazos, First I apologize to my ugly English.

I am happy that my project is helping someone. You can use it. I'll add the license soon. You can also apply the code that you have already created.

This application has been used by over 100 people and has proven to work without problems. It was distributed in a small community without using it in the Play Store.

Currently I am working on a different account. But please keep in mind that this account is alive, so please let me know if you have any questions in the future.

Thank you.
